<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="10" total="13" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="MySuite" duration-ms="69597" started-at="2020-12-06T13:13:34 WIB" finished-at="2020-12-06T13:14:44 WIB">
    <groups>
    </groups>
    <test name="Run devices 2" duration-ms="69597" started-at="2020-12-06T13:13:34 WIB" finished-at="2020-12-06T13:14:44 WIB">
      <class name="TestCases.TopNavigationTest">
        <test-method status="FAIL" signature="B_001()[pri:0, instance:TestCases.TopNavigationTest@6ee52dcd]" name="B_001" duration-ms="30214" started-at="2020-12-06T13:13:39 WIB" finished-at="2020-12-06T13:14:09 WIB">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
text hello guest is not exist did not expect to find [true] but found [false],
Logout button should not be exist, but its exist did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
text hello guest is not exist did not expect to find [true] but found [false],
Logout button should not be exist, but its exist did not expect to find [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestCases.TopNavigationTest.B_001(TopNavigationTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B_001 -->
        <test-method status="PASS" signature="resetApplicationState()[pri:0, instance:TestCases.TopNavigationTest@6ee52dcd]" name="resetApplicationState" is-config="true" duration-ms="6900" started-at="2020-12-06T13:14:12 WIB" finished-at="2020-12-06T13:14:19 WIB">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetApplicationState -->
      </class> <!-- TestCases.TopNavigationTest -->
      <class name="TestCases.HomePageTest">
        <test-method status="PASS" signature="C_001()[pri:0, instance:TestCases.HomePageTest@4493d195]" name="C_001" duration-ms="20717" started-at="2020-12-06T13:14:19 WIB" finished-at="2020-12-06T13:14:40 WIB">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C_001 -->
        <test-method status="PASS" signature="resetApplicationState()[pri:0, instance:TestCases.HomePageTest@4493d195]" name="resetApplicationState" is-config="true" duration-ms="4415" started-at="2020-12-06T13:14:40 WIB" finished-at="2020-12-06T13:14:44 WIB">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetApplicationState -->
      </class> <!-- TestCases.HomePageTest -->
      <class name="TestCases.LaunchWebTest">
        <test-method status="PASS" signature="a_SetUpAppium(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:TestCases.LaunchWebTest@704a52ec]" name="a_SetUpAppium" is-config="true" duration-ms="17098" started-at="2020-12-06T13:13:17 WIB" finished-at="2020-12-06T13:13:34 WIB">
          <params>
            <param index="0">
              <value>
                <![CDATA[beta]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sg]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[4723]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[RR8M901GK6R]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Galaxy A50s]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[aws]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a_SetUpAppium -->
        <test-method status="PASS" signature="deleteScreenShot()[pri:0, instance:TestCases.LaunchWebTest@704a52ec]" name="deleteScreenShot" is-config="true" duration-ms="2" started-at="2020-12-06T13:13:34 WIB" finished-at="2020-12-06T13:13:34 WIB">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteScreenShot -->
        <test-method status="FAIL" signature="A_001()[pri:0, instance:TestCases.LaunchWebTest@704a52ec]" name="A_001" duration-ms="145" started-at="2020-12-06T13:13:34 WIB" finished-at="2020-12-06T13:13:35 WIB">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[URL is found did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: URL is found did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at TestCases.LaunchWebTest.A_001(LaunchWebTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A_001 -->
        <test-method status="PASS" signature="resetApplicationState()[pri:0, instance:TestCases.LaunchWebTest@704a52ec]" name="resetApplicationState" is-config="true" duration-ms="3879" started-at="2020-12-06T13:13:35 WIB" finished-at="2020-12-06T13:13:39 WIB">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetApplicationState -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:TestCases.LaunchWebTest@704a52ec]" name="quitDriver" is-config="true" duration-ms="595" started-at="2020-12-06T13:14:44 WIB" finished-at="2020-12-06T13:14:45 WIB">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- TestCases.LaunchWebTest -->
    </test> <!-- Run devices 2 -->
  </suite> <!-- MySuite -->
</testng-results>
